/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.setting;

/**
 *
 * @author HP_RYZEN
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        lblMenuAlimentos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMenuMantenimiento = new javax.swing.JLabel();
        lblMenuAlimentos = new javax.swing.JLabel();
        lblMenuProgramacion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(34, 45, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuMantenimiento.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblMenuMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/menu_config.png"))); // NOI18N
        lblMenuMantenimiento.setText("MANTENIMIENTO");
        jPanel2.add(lblMenuMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, 40));

        lblMenuAlimentos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblMenuAlimentos.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuAlimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/menu_config.png"))); // NOI18N
        lblMenuAlimentos.setText("ALIMENTOS");
        jPanel2.add(lblMenuAlimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 40));

        lblMenuProgramacion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblMenuProgramacion.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuProgramacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/menu_config.png"))); // NOI18N
        lblMenuProgramacion.setText("PROGRAMACION");
        jPanel2.add(lblMenuProgramacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 490));

        jPanel3.setBackground(new java.awt.Color(60, 141, 188));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 60));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 630, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblMenuAlimentos;
    private javax.swing.JLabel lblMenuMantenimiento;
    private javax.swing.JLabel lblMenuProgramacion;
    // End of variables declaration//GEN-END:variables
}
